# Generated by Django 4.1.7 on 2023-03-28 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0006_remove_employee_address_remove_employee_email_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeeproject',
            unique_together={('employee', 'project')},
        ),
    ]
