# Generated by Django 4.1.7 on 2023-04-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0007_alter_employeeproject_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employment_start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(null=True),
        ),
    ]
