# Generated by Django 4.1.7 on 2023-04-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0008_employee_employment_start_date_employee_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
