# Generated by Django 4.1.7 on 2023-04-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0009_employee_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='lead_id',
        ),
        migrations.AddField(
            model_name='department',
            name='budget',
            field=models.IntegerField(null=True),
        ),
    ]
